import { SignatureData } from "./types";

export const academicSample: SignatureData = {
  fullName: "Hamid Reza Alami",
  pronouns: "",
  role: "Software Engineering Student",
  department: "School of Computer Science",
  organization: "Example University",
  degree: "Bachelor of Information Technology",
  studentId: "A1234567",
  researchArea: "Accessible web tooling, email compatibility, and AI-assisted software engineering",
  email: "hamid.alami@example.edu.au",
  phone: "+61 400 123 456",
  website: "https://example.edu.au/profile/hamid",
  location: "Adelaide, Australia",
  linkedin: "https://linkedin.com/in/yourprofile",
  github: "https://github.com/yourusername",
  orcid: "https://orcid.org/0000-0000-0000-0000",
  googleScholar: "https://scholar.google.com",
  bookingUrl: "",
  photoUrl: "",
  logoUrl: "",
  accentColor: "#111111",
  disclaimerRegion: "au",
};

export const professionalSample: SignatureData = {
  fullName: "Avery Chen",
  pronouns: "they/them",
  role: "Senior Product Engineer",
  department: "Platform Team",
  organization: "Northline Digital",
  degree: "",
  studentId: "",
  researchArea: "Frontend architecture, design systems, and accessibility",
  email: "avery.chen@example.com",
  phone: "+1 415 555 0199",
  website: "https://example.com",
  location: "San Francisco, CA",
  linkedin: "https://linkedin.com/in/example",
  github: "https://github.com/example",
  orcid: "",
  googleScholar: "",
  bookingUrl: "https://cal.com/example",
  photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
  logoUrl: "https://dummyimage.com/120x40/111111/ffffff.png&text=ND",
  accentColor: "#CC0000",
  disclaimerRegion: "us",
};

